HomeWorkTestng
Julwas/AQA21 pull request #1
Opened 2023-06-26 11:54 UTC by Julwas

2023-06-26 12:45 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +    public void divInt_2(){
Почему присутствуют тесты на INT - если по заданию все должно быть реализовано для Double?

2023-06-26 12:46 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +@Test(enabled = false, priority = 7, groups = "Double")
Отсутствуют тесты:
1) dataProvider
2) dependsOnMethod
3) invocationCount
4) timeout
5) retryAnalizer
6) parameter

2023-06-27 14:29 UTC, Julwas commented on src/test/java/HomeWorkTest.java
> +@Test(enabled = false, priority = 7, groups = "Double")
Добавила тесты: dataProvider, dependsOnMethod, invocationCount, timeout. 
Для теста parameter нужно создать отдельный файл xml?

2023-07-03 19:31 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +@Test(enabled = false, priority = 7, groups = "Double")
Да

2023-07-03 19:34 UTC, wildpioneer requested changes

2023-07-03 19:34 UTC, wildpioneer commented on src/main/java/Calculator.java
> +        if (b==0) {
В условии не было упоминания, что надо как-то обрабатывать данные в методе

2023-07-03 19:34 UTC, wildpioneer commented on src/main/java/Calculator.java
> +    public int divInt(int a, int b){
Почему методы имеют разные названия?

2023-07-03 19:34 UTC, wildpioneer commented on src/main/java/Calculator.java
> +        return (int) (a / b);
Почему деление двух double приводиться в int?

2023-07-03 19:34 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +        double actualValue = calculator.divDouble(0.0, 0.0);
После того как переделаешь сам метод деления - нужно переделать все проверки деления на 0

2023-07-23 11:16 UTC, wildpioneer commented
Проверено

2023-07-23 11:16 UTC, closed without merging