Selenium_wd_hw
Julwas/AQA21 pull request #2
Opened 2023-07-03 10:08 UTC by Julwas

2023-07-03 19:43 UTC, wildpioneer requested changes

2023-07-03 19:43 UTC, wildpioneer commented on src/test/java/data/SmokeTestHomeWork.java
> +    @BeforeMethod
1. Форматирование: пустая строка после переменных
2. Отсутствует ReadProperties.java в repository - и поэтому ничего не компилируется
3. Отсутствует SimpleDriver.java
4. Отсутствует config.properties

2023-07-04 06:29 UTC, Julwas commented on src/test/java/data/SmokeTestHomeWork.java
> +    @BeforeMethod
В идее и меня есть все эти файлы ReadProperties.java  и config.properties не перестают быть красными и не загружаются со всем поектом в github

2023-07-04 07:51 UTC, Julwas commented on src/test/java/data/SmokeTestHomeWork.java
> +    @BeforeMethod
исправлено

2023-07-10 06:02 UTC, wildpioneer commented
Проверено. Исправил ошибки с JUnit

2023-07-10 06:02 UTC, closed without merging