pageObgect_HW
Julwas/AQA21 pull request #3
Opened 2023-07-23 14:42 UTC by Julwas

2023-07-31 10:53 UTC, wildpioneer requested changes

2023-07-31 10:53 UTC, wildpioneer commented on target/ReadMe.md
> +
Папку target ни при каких условия нельзя комитить

2023-07-31 10:53 UTC, wildpioneer commented on src/test/java/E2ETest.java
> +        Assert.assertTrue(productsStep.AddProdusts().isPageOpened());
У меня тест падает здесь:
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#checkout"}

2023-07-31 10:53 UTC, wildpioneer commented on src/test/java/Steps/CheckoutStep.java
> +package Steps;
А почему папка Steps с большой - это не по code convention

2023-07-31 10:53 UTC, wildpioneer commented on src/test/java/pages/CartPage.java
> +    private final By headerCartTitleLocator = By.xpath("//*[@id='header_container']/div[2]/span");
Не совсем корректный xPath

2023-07-31 20:25 UTC, Julwas commented on target/ReadMe.md
> +
теперь буду знать)

2023-07-31 20:45 UTC, Julwas commented on src/test/java/Steps/CheckoutStep.java
> +package Steps;
исправила

2023-07-31 20:45 UTC, Julwas commented on src/test/java/pages/CartPage.java
> +    private final By headerCartTitleLocator = By.xpath("//*[@id='header_container']/div[2]/span");
исправила

2023-07-31 20:46 UTC, Julwas commented on src/test/java/E2ETest.java
> +        Assert.assertTrue(productsStep.AddProdusts().isPageOpened());
Исправила тест, перестал падать, проверяйте пожалуйста

2023-08-07 13:12 UTC, wildpioneer commented
Проверено

2023-08-07 13:12 UTC, closed without merging